spring:
  application:
    name: backend-springboot
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

app:
  security:
    cognito:
      client-id: ${COGNITO_CLIENT_ID}